# Analytics v${version} - https://tebex.io
# Check out https://docs.tebex.io/analytics if you need help.

hooks:
  # Enable or disable the plugin's hooks.
  placeholderapi:
    enabled: false
    enabled-stats:
      - 'enter_placeholder_here'
  floodgate:
    enabled: false

settings:
  # Excluded Players (UUID)
  # Players listed here will not be tracked by Analytics.
  excluded-players: []

  # Bedrock Username Prefix
  # The prefix to distinguish between Java and Bedrock players.
  #
  # Note: It will use the prefix from the floodgate plugin
  # when 'hooks.floodgate.enabled' is set to 'true'.
  bedrock-prefix: "."

  # Minimum Playtime (Seconds)
  # Only track players who have played for at least this amount of time.
  # Set to 0 to disable.
  minimum-playtime: 0

  # Use Server Playtime
  # Use the date the player joined your server as their first session,
  # instead of when they first joined Analytics.
  use-server-playtime: true

  # Use Proxy Mode
  # Enable this if you are running Analytics within a proxy such as BungeeCord, Velocity, etc.
  # This also requires you to download our proxy plugin.
  proxy-mode: false

# These settings are exclusive to this server.
# Do not share these credentials with anyone.
server:
  # Server Token
  # This is used to identify your server.
  token: ''

  # Encryption Key
  # This is used to encrypt sensitive data such as IP addresses.
  encryption-key: ''

# Configuration Version
# !! Do not change this value !!
config-version: 2